// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9NRy7Yw-Hc8O_8Zi6EupA7EDnZAeXj_A',
    appId: '1:399519416073:web:535b976dddcbd1d57d9dd8',
    messagingSenderId: '399519416073',
    projectId: 'movies-app-3267e',
    authDomain: 'movies-app-3267e.firebaseapp.com',
    storageBucket: 'movies-app-3267e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRpXfy9j-x6WY26NAYNf_ai2KgrsPiIg',
    appId: '1:399519416073:android:8d474aaf9f08785d7d9dd8',
    messagingSenderId: '399519416073',
    projectId: 'movies-app-3267e',
    storageBucket: 'movies-app-3267e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKBOJZHCAE3LXHiQ-BKEjGYzqa5xuSI0',
    appId: '1:399519416073:ios:b59f322be70f0f5c7d9dd8',
    messagingSenderId: '399519416073',
    projectId: 'movies-app-3267e',
    storageBucket: 'movies-app-3267e.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKKBOJZHCAE3LXHiQ-BKEjGYzqa5xuSI0',
    appId: '1:399519416073:ios:b59f322be70f0f5c7d9dd8',
    messagingSenderId: '399519416073',
    projectId: 'movies-app-3267e',
    storageBucket: 'movies-app-3267e.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9NRy7Yw-Hc8O_8Zi6EupA7EDnZAeXj_A',
    appId: '1:399519416073:web:cbd1af6c6eeaf5147d9dd8',
    messagingSenderId: '399519416073',
    projectId: 'movies-app-3267e',
    authDomain: 'movies-app-3267e.firebaseapp.com',
    storageBucket: 'movies-app-3267e.firebasestorage.app',
  );
}
